### ISSUE TITLE
Could not find test files

### ISSUE THREAD

**Issue by cliffeby** [tsmean/tsmean#1]
I cloned and installed repo from the command line.  **npm start** starts the server, but **npm test** creates this error

    ```
> ts-mongo-express-node-seed@0.0.0 test C:\Users\cliff\WebstormProjects\projectname\backend
    > mocha --reporter spec --compilers ts:ts-node/register '**/*.test.ts'

    Warning: Could not find any test files matching pattern: '**/*.test.ts'
    No test files found
    npm ERR! Test failed.  See above for more details.
```

**Comment by bersling** [comment]
I didn't test with Windows yet, sorry.

**Comment by cliffeby** [comment]
The logger test runs when run individually with Webstorm.  Others fail with various errors.  

I'm moving from Angular 1, but not good with testing frameworks.  Let me know if I can help.

-----Original Message-----

**Comment by bersling** [comment]
I think the problem lies with wildcards and windows. So what happens when you enter `npm test` is it expands to `mocha --reporter spec --compilers ts:ts-node/register '**/*.test.ts'`. Now I think windows can't handle the unix style ` '**/*.test.ts'`. One way would be to move all test files into a `test` folder, but that doesn't seem that satisfying. Here a similar issue is discussed: https://stackoverflow.com/questions/10753288/how-to-specify-test-directory-for-mocha/13059231 but I don't think many people with windows are around. I'll tried to fix it but couldn't achieve it yet, sorry. If you find a fix, let me know! You could try creating a `test` folder wich `mocha.opts` and the `--recursive` flag or something similar. I'll also try to find someone who could fix this.

**Comment by VishalBirth** [comment]
@bersling @cliffeby  for windows please use this. 
"test": "mocha --reporter spec --compilers ts:ts-node/register **\\*.test.ts", 
I hope this will solve your problem. :)

**Comment by bersling** [comment]
@VishalBirth I have merged your pull request. @cliffeby let me know if it works for you

**Comment by cliffeby** [comment]
Yes.  It works for me.

I noticed what appears to be a typo on line 18 api.model.ts.  I would have
offered a pull request, but can't figure out a test for the interface.

**Comment by bersling** [comment]
Thanks for spotting that, I fixed it
