### ISSUE TITLE
Question : where I found and do to authentificate ?

### ISSUE THREAD

**Issue by Paul75** [tsmean/tsmean#32]
Hello,

I want to know when i can use swagger ? In all request ask me that it denied.

Where I find the authorisation key (apiKey) ?

Thanks

**Comment by AngelMunoz** [comment]
to use swagger please try this url
`http://localhost:4242/api/swagger/#/` and the endpoints should be already usable

**Comment by Paul75** [comment]
I do this you say but always return : 
```
{
  "statusCode": 403,
  "message": "Forbidden resource"
}
```

Thanks

**Comment by AngelMunoz** [comment]
I think you are trying to visit with the browser right?
if so, the urls are not public for safety reasons, your application when runs sends an Authentication header, something like this
`Àuthentication: "Bearer [JSON Web Token]`
so, when you visit via the browser you don't send that header, that's why it says "Forbidden",  you need to use a tool like [Postman](https://www.getpostman.com/docs/v6/postman/sending_api_requests/authorization)
where you pick your token from the browser's local storage and send it through there.


**Edit:** You can comment this line  and it should not show you "Forbidden" https://github.com/tsmean/tsmean/blob/master/backend/src/app.module.ts#L16 
**But it is not recommended for production**
